---
title: "Coxph models"
author: "João Brandão"
date: "2024-03-25"
output: html_document
---

# Elastic net

## Univariate Analysis

```{r}

## Prepare data ##
  
sel.genes <- cv_genes.EN[[6]]
xdata.EN <- data.matrix(xdata[, sel.genes])
  
# Merge into a single data frame - needed for univariate cox
data.EN <- data.frame(merge(x = ydata, y = xdata.EN,
                              by = "row.names" , all.x = TRUE))
rownames(data.EN) <- data$Row.names
data.EN <- data.EN[, -1] # remove row name column 
data.EN$status <- as.numeric(data.EN$status) - 1 # correct status values
  
ydata.EN <- data.matrix(ydata)
ydata.EN[,2] <- ydata.EN[,2] - 1 # correction of the status values


## Univariate Cox model - for gene selection ##
  
univ_formulas <- sapply(sel.genes,
                      function(x) as.formula(paste('Surv(time, status)~', x)))
univ_models <- lapply(univ_formulas, function(x){coxph(x, data = data.EN)})

# Extract data 
univ_results <- lapply(univ_models,
                       function(x){ 
                         x <- summary(x)
                         p.value <-signif(x$wald["pvalue"], digits=2)
                         wald.test<-signif(x$wald["test"], digits=2)
                         beta<-signif(x$coef[1], digits=2);#coeficient beta
                         HR <-signif(x$coef[2], digits=2);#exp(beta)
                         HR.confint.lower <- signif(x$conf.int[,"lower .95"], 2)
                         HR.confint.upper <- signif(x$conf.int[,"upper .95"],2)
                         HR <- paste0(HR, " (", 
                                      HR.confint.lower, "-", HR.confint.upper, ")")
                        
                         res<-c(beta, HR, wald.test, p.value)
                         names(res)<-c("beta", "HR (95% CI for HR)", "wald.test", 
                                       "p.value")
                         return(res)
  })
  
res <- t(as.data.frame(univ_results, check.names = FALSE))
res <- as.data.frame(res)

# Selected variables
genes.EN <- rownames(res[which(p.adjust(res$p.value, method = "BH") <= 0.2),])

# Data with selected variables
xdata.EN <- data.frame(xdata[, genes.EN])
ydata.EN <- data.frame(ydata.EN) 
data.EN <- cbind(ydata.EN, xdata.EN)
data.train.EN <- cbind(y_train, x_train[, genes.EN])
data.test.EN <- cbind(y_test, x_test[, genes.EN])
    
```

## Coxph model

```{r}

cox.EN <- coxph(Surv(time , status) ~ . , data = data.EN)
cox.EN

ph_test.EN <- cox.zph(cox.EN, transform="km", terms=TRUE, singledf=FALSE, global=TRUE)
pvalue_ph.EN <- ph_test.EN$table[length(genes.EN)+1, 3]
pvalue_ph.EN

```

## C-index

```{r}

(Cindex.EN <- as.vector(survConcordance(Surv(time, status) ~ predict(cox.EN), data.EN)$concordance)) # or summary(cox.EN)$concordance[1]

```

## Log-rank

```{r}

sc.EN <- separate2GroupsCox(cox.EN$coefficients, 
                                  xdata.EN,
                                  ydata.EN, 
                                  plot.title = "", 
                                  legend.outside = FALSE)
sc.EN

```

# Hub Cox

## Univariate Analysis

```{r}

## Prepare data ##
  
sel.genes <- cv_genes.HC[[9]]
xdata.HC <- data.matrix(xdata[, sel.genes])
  
# Merge into a single data frame - needed for univariate cox
data.HC <- data.frame(merge(x = ydata, y = xdata.HC,
                              by = "row.names" , all.x = TRUE))
rownames(data.HC) <- data$Row.names
data.HC <- data.HC[, -1] # remove row name column 
data.HC$status <- as.numeric(data.HC$status) - 1 # correct status values
  
ydata.HC <- data.matrix(ydata)
ydata.HC[,2] <- ydata.HC[,2] - 1 # correction of the status values


## Univariate Cox model - for gene selection ##
  
univ_formulas <- sapply(sel.genes,
                      function(x) as.formula(paste('Surv(time, status)~', x)))
univ_models <- lapply(univ_formulas, function(x){coxph(x, data = data.HC)})

# Extract data 
univ_results <- lapply(univ_models,
                       function(x){ 
                         x <- summary(x)
                         p.value <-signif(x$wald["pvalue"], digits=2)
                         wald.test<-signif(x$wald["test"], digits=2)
                         beta<-signif(x$coef[1], digits=2);#coeficient beta
                         HR <-signif(x$coef[2], digits=2);#exp(beta)
                         HR.confint.lower <- signif(x$conf.int[,"lower .95"], 2)
                         HR.confint.upper <- signif(x$conf.int[,"upper .95"],2)
                         HR <- paste0(HR, " (", 
                                      HR.confint.lower, "-", HR.confint.upper, ")")
                        
                         res<-c(beta, HR, wald.test, p.value)
                         names(res)<-c("beta", "HR (95% CI for HR)", "wald.test", 
                                       "p.value")
                         return(res)
  })
  
res <- t(as.data.frame(univ_results, check.names = FALSE))
res <- as.data.frame(res)

# Selected variables
genes.HC <- rownames(res[which(p.adjust(res$p.value, method = "BH") <= 0.2),])

# Data with selected variables
xdata.HC <- data.frame(xdata[, genes.HC])
ydata.HC <- data.frame(ydata.HC) 
data.HC <- cbind(ydata.HC, xdata.HC)
data.train.HC <- cbind(y_train, x_train[, genes.HC])
data.test.HC <- cbind(y_test, x_test[, genes.HC])
    
```

## Coxph model

```{r}

cox.HC <- coxph(Surv(time , status) ~ . , data = data.HC)
cox.HC

ph_test.HC <- cox.zph(cox.HC, transform="km", terms=TRUE, singledf=FALSE, global=TRUE)
pvalue_ph.HC <- ph_test.HC$table[length(genes.HC)+1, 3]
pvalue_ph.HC

```

## C-index

```{r}

(Cindex.HC <- as.vector(survConcordance(Surv(time, status) ~ predict(cox.HC), data.HC)$concordance)) # or summary(cox.HC)$concordance[1]

```

## Log-rank

```{r}

# Train
sc.HC <- separate2GroupsCox(cox.HC$coefficients, 
                                  xdata.HC, 
                                  ydata.HC, 
                                  plot.title = "", 
                                  legend.outside = FALSE)
sc.HC

```

# Orphan Cox

## Univariate Analysis

```{r}

## Prepare data ##
  
sel.genes <- cv_genes.OC[[7]]
xdata.OC <- data.matrix(xdata[, sel.genes])
  
# Merge into a single data frame - needed for univariate cox
data.OC <- data.frame(merge(x = ydata, y = xdata.OC,
                              by = "row.names" , all.x = TRUE))
rownames(data.OC) <- data$Row.names
data.OC <- data.OC[, -1] # remove row name column 
data.OC$status <- as.numeric(data.OC$status) - 1 # correct status values
  
ydata.OC <- data.matrix(ydata)
ydata.OC[,2] <- ydata.OC[,2] - 1 # correction of the status values


## Univariate Cox model - for gene selection ##
  
univ_formulas <- sapply(sel.genes,
                      function(x) as.formula(paste('Surv(time, status)~', x)))
univ_models <- lapply(univ_formulas, function(x){coxph(x, data = data.OC)})

# Extract data 
univ_results <- lapply(univ_models,
                       function(x){ 
                         x <- summary(x)
                         p.value <-signif(x$wald["pvalue"], digits=2)
                         wald.test<-signif(x$wald["test"], digits=2)
                         beta<-signif(x$coef[1], digits=2);#coeficient beta
                         HR <-signif(x$coef[2], digits=2);#exp(beta)
                         HR.confint.lower <- signif(x$conf.int[,"lower .95"], 2)
                         HR.confint.upper <- signif(x$conf.int[,"upper .95"],2)
                         HR <- paste0(HR, " (", 
                                      HR.confint.lower, "-", HR.confint.upper, ")")
                        
                         res<-c(beta, HR, wald.test, p.value)
                         names(res)<-c("beta", "HR (95% CI for HR)", "wald.test", 
                                       "p.value")
                         return(res)
  })
  
res <- t(as.data.frame(univ_results, check.names = FALSE))
res <- as.data.frame(res)

# Selected variables
genes.OC <- rownames(res[which(p.adjust(res$p.value, method = "BH") <= 0.2),])

# Data with selected variables
xdata.OC <- data.frame(xdata[, genes.OC])
ydata.OC <- data.frame(ydata.OC) 
data.OC <- cbind(ydata.OC, xdata.OC)
data.train.OC <- cbind(y_train, x_train[, genes.OC])
data.test.OC <- cbind(y_test, x_test[, genes.OC])
    
```

## Coxph model

```{r}

cox.OC <- coxph(Surv(time , status) ~ . , data = data.OC)
cox.OC

ph_test.OC <- cox.zph(cox.OC, transform="km", terms=TRUE, singledf=FALSE, global=TRUE)
pvalue_ph.OC <- ph_test.OC$table[length(genes.OC)+1, 3]
pvalue_ph.OC

```

## C-index

```{r}

(Cindex.OC <- as.vector(survConcordance(Surv(time, status) ~ predict(cox.OC), data.OC)$concordance)) # or summary(cox.OC)$concordance[1]

```

## Log-rank

```{r}

# Train
sc.OC <- separate2GroupsCox(cox.OC$coefficients, 
                                  xdata.OC, 
                                  ydata.OC, 
                                  plot.title = "", 
                                  legend.outside = FALSE)
sc.OC

```

# Table Results

```{r}

# models summary

table_result <- data.frame(rbind(
cbind("Elastic Net", length(genes.EN), round(pvalue_ph.EN,4), round(Cindex.EN,4), round(sc.EN$pvalue,4)),
cbind("Hub Cox", length(genes.HC), round(pvalue_ph.HC,4), round(Cindex.HC,4), round(sc.HC$pvalue,4)),
cbind("Orphan Cox", length(genes.OC), round(pvalue_ph.OC,4), round(Cindex.OC,4), round(sc.OC$pvalue,4))
))

colnames(table_result) <- c("Model", "N_covariates", "PH_pvalue", "C_index", "LR_pvalue")

table_result

```

